feat: add Request::getBestAcceptEncoding() function
pistacheio/pistache pull request #1165
Opened 2023-10-22 17:30 UTC by Tachi107

The new getBestAcceptEncoding() function makes using the new compression support introduced in commit b0b7d3076dcdba48935cfe14049b76809d0cd256 way easier, as it reports to the caller the most sensible content encoding to apply to the response, falling back to the Identity encoding (i.e. no actual compression) in case no encoding is supported by both the server and the client.

Fixes https://github.com/pistacheio/pistache/issues/1148

2023-10-22 17:38 UTC, kiplingw approved these changes
Solid work @Tachi107. LGTM. @dennisjenkins75, have a look over. If you're fine with it lets merge.

2023-10-22 20:24 UTC, Tachi107 commented
Added some more tests and fixed a corner case discovered with the newly added tests. Should be ready now :)

2023-10-22 20:28 UTC, kiplingw commented
@Tachi107, if your PR passes in CI and @dennisjenkins75 has had a chance to review, I'm totally fine with it. Only thing I'd suggest changing is to bump the patch version.

2023-10-22 20:30 UTC, Tachi107 commented
> Only thing I'd suggest changing is to bump the patch version.

Done

2023-10-22 20:40 UTC, Tachi107 commented
Debian testing CI runs are failing the Coverage step because of Debian bug <https://bugs.debian.org/1053252>, it's unrelated to this patch set.

2023-10-22 23:24 UTC, dennisjenkins75 requested changes

2023-10-22 23:24 UTC, dennisjenkins75 commented on include/pistache/http.h
> +             * Returns the "best" encoding to use to encode (tipically compress)
"typically"

2023-10-24 09:03 UTC, Tachi107 commented on include/pistache/http.h
> +             * Returns the "best" encoding to use to encode (tipically compress)
Thanks, fixed!

2023-10-24 14:36 UTC, merged

2023-10-24 19:00 UTC, Tachi107 commented
Thanks for the review and merge :)